services:
  elixir:
    image: elixir:1.17
    container_name: elixir
    stdin_open: true # keep stdin open even if not attached
    tty: true # allocate a pseudo-TTY
    ports:
      - "4000:4000"
    environment:
      DB_USER: usuario
      DB_PASSWORD: secret
      DB_NAME: elixir
      DB_HOST: db
      DB_PORT: "3306"
    volumes:
      - ./:/home/program
    command: bash
    networks:
      - metaprograming

  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: elixir
      MYSQL_USER: usuario
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - metaprograming

  db_posgrest:
    image: postgres
    container_name: posgrest-db-meta
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user12345
      POSTGRES_DB: meta_database
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data postgres
    ports:
      - "3300:3300"
    networks:
      - metaprograming

networks:
  metaprograming:
    driver: bridge
# docker exec -it elixir /bin/bash
# docker exec -it mysql mysql -u root -p